### PR TITLE
Add results plotting script

### PR DESCRIPTION
**Pull request by cnpryer**
image

Not sure how *exactly* you'd like to do this, but here's a go 🤷‍♂️ cc: @chitralverma

### CODE REVIEW

**Comment by chitralverma** [comment]
Thanks, I'll check it out

**Comment by chitralverma** [comment]
Thanks, I'll check it out

**Comment by chitralverma** [comment]
Hi @cnpryer, mostly it looks good to me, can you try updating your branch with the latest upsteam.
Let me know, i will merge it after.

**Comment by ritchie46** [comment]
> Hi @cnpryer, mostly it looks good to me, can you try updating your branch with the latest upsteam. Let me know, i will merge it after.

As @chitralverma review was fine and it looks good to me as well, I merged it in.

**Pull request merged**
